spring:
    datasource:
        url: jdbc:mysql://localhost:3308/core_products
        username: username
        password: password
        hikari:
            poolName: HikariCP
            maximumPoolSize: 5
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true

server:
    port: 8082

