services:
    mysql:
        container_name: core_products
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: core_products
            MYSQL_USER: username
            MYSQL_PASSWORD: password
        ports:
            - "3308:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - mysql_network
        restart: unless-stopped

networks:
    mysql_network:

volumes:
    mysql_data:
        driver: local
